name: Build and run Sanitizer

on:
  workflow_call:
    inputs:
      sanitizer-name:
        description: Sanitizer name (asan/msan/tsan/ubsan)
        type: string
        required: true

jobs:
  build_and_run_sanitizer:
    name: Build and run Sanitizer
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build BlazingMQ and dependencies with sanitizer instrumentation
        run: ${{ github.workspace }}/.github/workflows/sanitizers/build_sanitizer.sh ${{ inputs.sanitizer-name }}
      - name: Run unit tests under sanitizer
        run: ${{ github.workspace }}/cmake.bld/Linux/run-unittests.sh
